### ISSUE TITLE
Red Ball Platform Oyunu - Temel Proje Yapısı

### ISSUE THREAD

**Issue by TheHuseyinYILDIZ** [TheHuseyinYILDIZ/ULTIMATE--BALL-STAR-GAME#1]
## Dosya Yapısı

Aşağıdaki dosya/klasör yapısı kurulacak:

```
/project-root
├── index.html
├── css/
│   └── styles.css
├── js/
│   ├── game.js
│   └── utils.js
├── assets/
│   ├── images/
│   └── sounds/
└── levels/
    ├── level1.json
    ├── level2.json
    └── level3.json
```

#### `index.html`
```html
<!DOCTYPE html>
<html lang="tr">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Red Ball Clone</title>
    <link rel="stylesheet" href="css/styles.css">
</head>
<body>
    <div id="game-container">
        <!-- Ana Menü -->
        <div id="main-menu">
            <h1>Red Ball Clone</h1>
            <h2>Platform Macerasına Hoş Geldiniz</h2>
            <button id="start-btn">Başlat</button>
            <button id="level-select-btn">Seviye Seç</button>
            <button id="settings-btn">Ayarlar</button>
        </div>

        <!-- Oyun Canvas -->
        <canvas id="gameCanvas" width="800" height="600"></canvas>
    </div>

    <script src="js/utils.js"></script>
    <script src="js/game.js"></script>
</body>
</html>
```

#### `css/styles.css`
```css
@import url('https://fonts.googleapis.com/css2?family=Nunito:wght@400;700&display=swap');

:root {
    --primary-color: #ff4444;
    --secondary-color: #333333;
    --background-color: #f0f0f0;
}

body {
    margin: 0;
    padding: 0;
    font-family: 'Nunito', sans-serif;
    background-color: var(--background-color);
    display: flex;
    justify-content: center;
    align-items: center;
    min-height: 100vh;
}

#game-container {
    position: relative;
    width: 800px;
    height: 600px;
    box-shadow: 0 0 20px rgba(0,0,0,0.2);
}

#main-menu {
    position: absolute;
    width: 100%;
    height: 100%;
    display: flex;
    flex-direction: column;
    justify-content: center;
    align-items: center;
    background: linear-gradient(135deg, #ff4444 0%, #ff6b6b 100%);
    color: white;
}

button {
    margin: 10px;
    padding: 15px 30px;
    font-size: 1.2em;
    border: none;
    border-radius: 25px;
    background: white;
    color: var(--primary-color);
    cursor: pointer;
    transition: transform 0.2s, box-shadow 0.2s;
}

button:hover {
    transform: translateY(-2px);
    box-shadow: 0 5px 15px rgba(0,0,0,0.2);
}

#gameCanvas {
    display: none;
    background: white;
}
```

#### `js/game.js`
Ana oyun mantığını içerecek temel yapı:

```javascript
class Game {
    constructor() {
        this.canvas = document.getElementById('gameCanvas');
        this.ctx = this.canvas.getContext('2d');
        this.ball = {
            x: 100,
            y: 100,
            radius: 20,
            speedX: 0,
            speedY: 0
        };
        this.setupEventListeners();
    }

    init() {
        // Oyun başlangıç ayarları
    }

    update() {
        // Oyun mantığı güncellemeleri
    }

    render() {
        // Canvas çizim işlemleri
    }

    gameLoop() {
        this.update();
        this.render();
        requestAnimationFrame(() => this.gameLoop());
    }

    setupEventListeners() {
        // Kontrol tuşları için event listener'lar
    }
}

// Oyun başlatma
document.addEventListener('DOMContentLoaded', () => {
    const game = new Game();
    // Ana menü kontrolleri
});
```

#### `js/utils.js`
Yardımcı fonksiyonları içerecek:

```javascript
const Utils = {
    collision: {
        checkCircleRect(circle, rect) {
            // Çember-dikdörtgen çarpışma kontrolü
        },
        
        checkCircleCircle(circle1, circle2) {
            // Çember-çember çarpışma kontrolü
        }
    },
    
    physics: {
        applyGravity(object) {
            // Yerçekimi hesaplaması
        },
        
        applyFriction(object) {
            // Sürtünme hesaplaması
        }
    },
    
    audio: {
        play(soundName) {
            // Ses efekti çalma
        },
        
        setVolume(type, level) {
            // Ses seviyesi ayarlama
        }
    }
};
```

#### `levels/level1.json`
```json
{
    "name": "Level 1",
    "targetTime": 60,
    "platforms": [
        {
            "x": 0,
            "y": 550,
            "width": 800,
            "height": 50,
            "type": "static"
        },
        {
            "x": 300,
            "y": 400,
            "width": 200,
            "height": 20,
            "type": "moving",
            "movement": {
                "startX": 300,
                "endX": 500,
                "speed": 2
            }
        }
    ],
    "enemies": [
        {
            "x": 400,
            "y": 500,
            "type": "patrol",
            "patrol": {
                "startX": 350,
                "endX": 450,
                "speed": 1
            }
        }
    ],
    "collectibles": [
        {
            "x": 200,
            "y": 300,
            "type": "coin"
        }
    ],
    "goal": {
        "x": 750,
        "y": 500
    }
}
```

## Sonraki Adımlar

1. Temel dosya yapısını oluştur
2. Ana menü tasarımını tamamla
3. Karakter (Red Ball) fizik sistemini implement et
4. Level yükleme sistemini kur
5. Çarpışma kontrollerini ekle
6. Ses sistemini entegre et
