### ISSUE TITLE
ORBVENTURE - Temel Dosya Yapısı ve Ana Menü

### ISSUE THREAD

**Issue by TheHuseyinYILDIZ** [TheHuseyinYILDIZ/ULTIMATE--BALL-STAR-GAME#2]
### index.html
```html
<!DOCTYPE html>
<html lang="tr">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>ORBVENTURE by STAR SOFTWARE</title>
    <link rel="stylesheet" href="css/styles.css">
    <link rel="icon" type="image/x-icon" href="assets/images/favicon.ico">
</head>
<body>
    <div id="game-container">
        <!-- Ana Menü -->
        <div id="main-menu" class="menu-screen">
            <div class="game-title">
                <h1>ORBVENTURE</h1>
                <div class="studio-name">by STAR SOFTWARE</div>
            </div>
            
            <div class="menu-buttons">
                <button id="start-btn" class="glow-button">BAŞLAT</button>
                <button id="level-select-btn" class="glow-button">SEVİYE SEÇ</button>
                <button id="settings-btn" class="glow-button">AYARLAR</button>
            </div>

            <div class="version">v1.0.0</div>
        </div>

        <!-- Seviye Seçim Ekranı -->
        <div id="level-select" class="menu-screen" style="display: none;">
            <h2>SEVİYE SEÇ</h2>
            <div class="level-grid">
                <!-- Seviyeler JavaScript ile doldurulacak -->
            </div>
            <button id="back-to-menu" class="glow-button">GERİ</button>
        </div>

        <!-- Ayarlar Ekranı -->
        <div id="settings" class="menu-screen" style="display: none;">
            <h2>AYARLAR</h2>
            <div class="settings-content">
                <div class="setting-group">
                    <label>Müzik Sesi</label>
                    <input type="range" id="music-volume" min="0" max="100" value="70">
                </div>
                <div class="setting-group">
                    <label>Efekt Sesi</label>
                    <input type="range" id="sfx-volume" min="0" max="100" value="80">
                </div>
                <div class="setting-group">
                    <label>Dil</label>
                    <select id="language">
                        <option value="tr">Türkçe</option>
                        <option value="en">English</option>
                    </select>
                </div>
            </div>
            <button id="settings-back" class="glow-button">KAYDET & GERİ</button>
        </div>

        <!-- Oyun Canvas -->
        <canvas id="gameCanvas" width="800" height="600" style="display: none;"></canvas>
    </div>

    <!-- Scripts -->
    <script src="js/utils.js"></script>
    <script src="js/menu.js"></script>
    <script src="js/game.js"></script>
</body>
</html>
```

### css/styles.css
```css
@import url('https://fonts.googleapis.com/css2?family=Orbitron:wght@400;700&display=swap');

:root {
    --primary-color: #00ff88;
    --secondary-color: #ff00ff;
    --background-color: #000033;
    --text-color: #ffffff;
    --menu-bg: rgba(0, 0, 51, 0.9);
}

* {
    margin: 0;
    padding: 0;
    box-sizing: border-box;
}

body {
    font-family: 'Orbitron', sans-serif;
    background-color: var(--background-color);
    color: var(--text-color);
    display: flex;
    justify-content: center;
    align-items: center;
    min-height: 100vh;
    overflow: hidden;
}

#game-container {
    position: relative;
    width: 800px;
    height: 600px;
    background: radial-gradient(circle at center, #000066 0%, #000033 100%);
    box-shadow: 0 0 30px rgba(0, 255, 136, 0.3);
    border-radius: 10px;
}

.menu-screen {
    position: absolute;
    width: 100%;
    height: 100%;
    display: flex;
    flex-direction: column;
    justify-content: center;
    align-items: center;
    background: var(--menu-bg);
    padding: 20px;
    border-radius: 10px;
}

.game-title {
    text-align: center;
    margin-bottom: 50px;
}

h1 {
    font-size: 4em;
    background: linear-gradient(45deg, var(--primary-color), var(--secondary-color));
    -webkit-background-clip: text;
    -webkit-text-fill-color: transparent;
    text-shadow: 0 0 10px rgba(0, 255, 136, 0.5);
    margin-bottom: 10px;
}

.studio-name {
    font-size: 1.2em;
    color: var(--primary-color);
    text-transform: uppercase;
    letter-spacing: 2px;
}

.menu-buttons {
    display: flex;
    flex-direction: column;
    gap: 20px;
}

.glow-button {
    padding: 15px 40px;
    font-size: 1.2em;
    font-family: 'Orbitron', sans-serif;
    color: var(--text-color);
    background: transparent;
    border: 2px solid var(--primary-color);
    border-radius: 25px;
    cursor: pointer;
    transition: all 0.3s ease;
    text-transform: uppercase;
    letter-spacing: 2px;
    position: relative;
    overflow: hidden;
}

.glow-button:hover {
    background: var(--primary-color);
    color: var(--background-color);
    box-shadow: 0 0 20px var(--primary-color);
    transform: translateY(-2px);
}

.glow-button:active {
    transform: translateY(0);
}

.version {
    position: absolute;
    bottom: 20px;
    right: 20px;
    font-size: 0.8em;
    color: var(--primary-color);
}

/* Seviye Seçim Ekranı Stilleri */
.level-grid {
    display: grid;
    grid-template-columns: repeat(3, 1fr);
    gap: 20px;
    margin: 30px 0;
}

.level-button {
    width: 120px;
    height: 120px;
    border: 2px solid var(--primary-color);
    border-radius: 10px;
    background: transparent;
    color: var(--text-color);
    font-family: 'Orbitron', sans-serif;
    cursor: pointer;
    transition: all 0.3s ease;
    display: flex;
    flex-direction: column;
    justify-content: center;
    align-items: center;
    gap: 10px;
}

.level-button:hover {
    background: var(--primary-color);
    color: var(--background-color);
    box-shadow: 0 0 15px var(--primary-color);
}

/* Ayarlar Ekranı Stilleri */
.settings-content {
    width: 80%;
    max-width: 400px;
    margin: 30px 0;
}

.setting-group {
    margin: 20px 0;
}

.setting-group label {
    display: block;
    margin-bottom: 10px;
    color: var(--primary-color);
}

input[type="range"] {
    width: 100%;
    height: 5px;
    background: var(--primary-color);
    border-radius: 5px;
    outline: none;
    opacity: 0.7;
    transition: opacity 0.2s;
}

input[type="range"]:hover {
    opacity: 1;
}

select {
    width: 100%;
    padding: 10px;
    background: transparent;
    border: 2px solid var(--primary-color);
    color: var(--text-color);
    font-family: 'Orbitron', sans-serif;
    border-radius: 5px;
}

select option {
    background: var(--background-color);
    color: var(--text-color);
}
```

### js/menu.js
```javascript
class MenuManager {
    constructor() {
        this.mainMenu = document.getElementById('main-menu');
        this.levelSelect = document.getElementById('level-select');
        this.settings = document.getElementById('settings');
        this.canvas = document.getElementById('gameCanvas');
        
        this.setupEventListeners();
        this.loadSettings();
    }

    setupEventListeners() {
        // Ana menü butonları
        document.getElementById('start-btn').addEventListener('click', () => this.startGame());
        document.getElementById('level-select-btn').addEventListener('click', () => this.showScreen('level-select'));
        document.getElementById('settings-btn').addEventListener('click', () => this.showScreen('settings'));

        // Geri butonları
        document.getElementById('back-to-menu').addEventListener('click', () => this.showScreen('main-menu'));
        document.getElementById('settings-back').addEventListener('click', () => {
            this.saveSettings();
            this.showScreen('main-menu');
        });

        // Ayarlar değişiklikleri
        document.getElementById('music-volume').addEventListener('change', (e) => {
            // Müzik ses seviyesini güncelle
            Utils.audio.setVolume('music', e.target.value / 100);
        });

        document.getElementById('sfx-volume').addEventListener('change', (e) => {
            // Efekt ses seviyesini güncelle
            Utils.audio.setVolume('sfx', e.target.value / 100);
        });
    }

    showScreen(screenId) {
        // Tüm ekranları gizle
        this.mainMenu.style.display = 'none';
        this.levelSelect.style.display = 'none';
        this.settings.style.display = 'none';
        this.canvas.style.display = 'none';

        // İstenen ekranı göster
        switch(screenId) {
            case 'main-menu':
                this.mainMenu.style.display = 'flex';
                break;
            case 'level-select':
                this.levelSelect.style.display = 'flex';
                this.createLevelGrid();
                break;
            case 'settings':
                this.settings.style.display = 'flex';
                break;
            case 'game':
                this.canvas.style.display = 'block';
                break;
        }
    }

    createLevelGrid() {
        const levelGrid = document.querySelector('.level-grid');
        levelGrid.innerHTML = ''; // Grid'i temizle

        // 9 seviye butonu oluştur
        for (let i = 1; i <= 9; i++) {
            const levelBtn = document.createElement('button');
            levelBtn.className = 'level-button';
            levelBtn.innerHTML = `
                <span class="level-number">Seviye ${i}</span>
                <span class="level-status">${i <= 3 ? 'Açık' : 'Kilitli'}</span>
            `;
            
            if (i <= 3) { // İlk 3 seviye açık
                levelBtn.addEventListener('click', () => this.startLevel(i));
            } else {
                levelBtn.disabled = true;
                levelBtn.style.opacity = '0.5';
            }
            
            levelGrid.appendChild(levelBtn);
        }
    }

    startGame() {
        this.showScreen('game');
        // Oyunu başlat
        const game = new Game();
        game.init(1); // Level 1'den başla
    }

    startLevel(levelNumber) {
        this.showScreen('game');
        // Seçilen seviyeyi başlat
        const game = new Game();
        game.init(levelNumber);
    }

    loadSettings() {
        // Local storage'dan ayarları yükle
        const settings = JSON.parse(localStorage.getItem('orbventure-settings')) || {
            musicVolume: 70,
            sfxVolume: 80,
            language: 'tr'
        };

        document.getElementById('music-volume').value = settings.musicVolume;
        document.getElementById('sfx-volume').value = settings.sfxVolume;
        document.getElementById('language').value = settings.language;

        // Ses seviyelerini ayarla
        Utils.audio.setVolume('music', settings.musicVolume / 100);
        Utils.audio.setVolume('sfx', settings.sfxVolume / 100);
    }

    saveSettings() {
        // Ayarları local storage'a kaydet
        const settings = {
            musicVolume: document.getElementById('music-volume').value,
            sfxVolume: document.getElementById('sfx-volume').value,
            language: document.getElementById('language').value
        };

        localStorage.setItem('orbventure-settings', JSON.stringify(settings));
    }
}

// Menü sistemini başlat
document.addEventListener('DOMContentLoaded', () => {
    window.menuManager = new MenuManager();
});
```

## Yapılacak İşlemler

1. Yukarıdaki dosyaları oluşturun
2. Dosya yapısını kontrol edin:
   ```
   /project-root
   ├── index.html
   ├── css/
   │   └── styles.css
   ├── js/
   │   ├── menu.js
   │   ├── game.js
   │   └── utils.js
   ├── assets/
   │   ├── images/
   │   │   └── favicon.ico
   │   └── sounds/
   └── levels/
       ├── level1.json
       ├── level2.json
       └── level3.json
   ```
3. Font'ları ve stilleri test edin
4. Menü geçişlerini test edin
5. Ayarlar ve localStorage çalışmasını kontrol edin

## Sonraki Adım
Bir sonraki adımda oyun motorunu (game.js) ve yardımcı fonksiyonları (utils.js) oluşturacağız.
